FROM python:3.11-slim

WORKDIR /app

COPY bot/requirements.txt .
RUN pip install -r requirements.txt
RUN pip install "python-telegram-bot[job-queue]==20.3"

# Copia SOLO i file necessari (escludi shared)
COPY bot /app

CMD ["python", "/app/bot.py"]
